using System.Collections.Generic; using UnityEngine;  public class panSelector : MonoBehaviour {     public Material highlightMat;     public Material normalMat;     private int highlighted;     public GameObject pan1, pan2, pan3;     public ParticleSystem smoke, lightt, burning;     public GameObject[] MyObjects;     public ParticleSystem[] particalSys;     Dictionary<GameObject, ParticleSystem[]> dict = new Dictionary<GameObject, ParticleSystem[]>();      // Start is called before the first frame update     void Start()     {         MyObjects = new GameObject[4];         MyObjects[1] = pan1;         MyObjects[2] = pan2;         MyObjects[3] = pan3;          GameObject s = MyObjects[2];         s.GetComponentInChildren<Renderer>().material = highlightMat;         highlighted = 2;          particalSys = new ParticleSystem[4];         particalSys[1] = smoke;         particalSys[2] = lightt;         particalSys[3] = burning;         dict.Add(pan1, particalSys);         dict.Add(pan2, particalSys);         dict.Add(pan3, particalSys);      }      // Update is called once per frame     void Update()     {          if (Input.GetKeyDown(KeyCode.D))         {             if((highlighted - 1) == 0)             {                 highlighted = 3;                 GameObject o = MyObjects[1];                 o.GetComponentInChildren<Renderer>().material = normalMat;                  GameObject p = MyObjects[highlighted];                 p.GetComponentInChildren<Renderer>().material = highlightMat;             }             else             {                 GameObject o = MyObjects[highlighted];                 o.GetComponentInChildren<Renderer>().material = normalMat;                  highlighted -= 1;                 GameObject p = MyObjects[highlighted];                 p.GetComponentInChildren<Renderer>().material = highlightMat;              }           }         else if (Input.GetKeyDown(KeyCode.A))         {             if ((highlighted + 1) == 4)             {                 highlighted = 1;                 GameObject o = MyObjects[3];                 o.GetComponentInChildren<Renderer>().material = normalMat;                  GameObject p = MyObjects[highlighted];                 p.GetComponentInChildren<Renderer>().material = highlightMat;             }             else             {                 GameObject o = MyObjects[highlighted];                 o.GetComponentInChildren<Renderer>().material = normalMat;                  highlighted += 1;                 GameObject p = MyObjects[highlighted];                 p.GetComponentInChildren<Renderer>().material = highlightMat;              }          }          if(Input.GetKeyDown(KeyCode.O) )         {             for (int i = 1; i < 4; i++)
            {
                ParticleSystem[] part = dict[MyObjects[i]];

                part[1].Stop();
                part[2].Stop();
                part[3].Stop();  
            }          }         else if(Input.GetKeyDown(KeyCode.P))
        {
            for (int i = 1; i < 4; i++)             {                 ParticleSystem[] part = dict[MyObjects[i]];                  part[1].Play();                 part[2].Play();                 part[3].Play();               }
        }      } }